# Site settings
title: Python ML Guide
description: "A beginner-friendly, step-by-step guide to Machine Learning with Python"
url: "https://shadowamitendu.github.io"
baseurl: "/python-ml-guide"
repository: ShadowAmitendu/python-ml-guide

# Theme: Midnight
theme: jekyll-theme-midnight

# Author
author:
  name: Amitendu

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalink style
permalink: /:year/:month/:day/:title/

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
